[package]
name = "actix-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.8.0", features = ["cookies"] }
oauth2 = "4.4.2"
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.118"
tlns-google-oauth2 = "0.4.0"
